import { boolean, integer, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/** uuid primary key generated by PostgreSQL (gen_random_uuid is core since PG13). */
export const id = () => uuid('id').primaryKey().defaultRandom();

/** created_at / updated_at; updated_at is maintained by the set_updated_at() trigger. */
export const timestamps = () => ({
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Columns shared by every lookup table. Lookups are never deleted while in use
 * (FKs are ON DELETE RESTRICT); they are retired with is_active = false so
 * historical rows keep resolving.
 */
export const lookupColumns = () => ({
  id: id(),
  key: text('key').notNull().unique(),
  name: text('name').notNull(),
  description: text('description'),
  sortOrder: integer('sort_order').notNull().default(0),
  isActive: boolean('is_active').notNull().default(true),
  ...timestamps(),
});

/** Machine keys are lower_snake_case so they are safe in URLs, JSON and code. */
export const KEY_PATTERN = '^[a-z][a-z0-9_]{0,62}$';
