-- Barebone CI core (SHAA-267).
--
-- Every CI keeps only what every CI has, whatever its class:
--   * ident: a short, readable, unique identifier ("CI-7K3M9Q2X", Crockford
--     base32), generated by the database. Only an administrator can change it
--     (enforced by the API, audited like any CI change);
--   * valid_from / valid_until: the validity period. A CI is *active* while
--     valid_from <= now() < valid_until (no valid_until: open-ended). "active"
--     is derived at query time, never stored;
--   * label: the display name of the CI, the value of its class's title
--     attribute (ci_classes.title_attribute_id) as text, or the ident when the
--     class has none or the CI holds no value. Derived and maintained by the
--     API; clients never write it.
-- plus the registry columns it already had (class, version, timestamps, soft delete).
--
-- The fixed columns name, hostname, ip_address, serial_number, notes, status_id,
-- environment_id, owner_id and location_id become ordinary class attributes:
--   * name (text, required) is added to every root class and becomes the title
--     attribute of every class;
--   * the other fields are added only to the classes whose CIs hold a value
--     (to the topmost such class of each lineage, so a subclass inherits it);
--   * status, environment, owner and location become lookup attributes. Their
--     rows are copied into the lookup lists "status", "environment", "owner"
--     and "location" (another key if one is taken) with the SAME ids, so a
--     stored id keeps meaning the same value. The old tables stay, unchanged
--     and no longer referenced by CIs, so owner e-mail addresses, location
--     hierarchy and similar details are kept; their endpoints are deprecated;
--   * a key already used in the class's lineage gets a suffix (name_2) and a
--     note in cmdb.schema_changes.
-- Every value is copied into the type tables and verified: per field, the
-- number of values written must equal the number of CIs that held one, or the
-- migration fails and nothing changes. Only then are the old columns dropped.
--
-- Stored UI settings (list columns, sorts, filters, dashboard widgets,
-- layouts) are rewritten to the new field names in a new settings version.
--
-- Reporting views (<area>.v_<type>) read the old columns; they are dropped
-- here and rebuilt by `shadoucmdb migrate` right after the migrations.
--
-- Operators can compare every value before and after the upgrade with
-- sql/checks/core_ci_upgrade_1_before.sql and _2_after.sql.

-- The backfills below are not edits: CIs and classes keep their updated_at.
ALTER TABLE cmdb.configuration_items DISABLE TRIGGER configuration_items_set_updated_at;
--> statement-breakpoint
ALTER TABLE cmdb.ci_classes DISABLE TRIGGER ci_classes_set_updated_at;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Ident
-- ---------------------------------------------------------------------------
-- 40 random bits as 8 Crockford base32 characters (no I, L, O, U), retried
-- until unused. The unique index below is the guarantee; the loop only makes a
-- collision (one in a trillion per pair) cost a retry instead of an error.
CREATE FUNCTION cmdb.new_ci_ident() RETURNS text
LANGUAGE plpgsql VOLATILE SET search_path = cmdb, public AS $$
DECLARE
  alphabet constant text := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
  bits bigint;
  candidate text;
BEGIN
  LOOP
    bits := ('x' || encode(substring(uuid_send(gen_random_uuid()) FROM 1 FOR 5), 'hex'))::bit(40)::bigint;
    candidate := 'CI-';
    FOR i IN 0..7 LOOP
      candidate := candidate || substr(alphabet, ((bits >> (35 - 5 * i)) & 31)::integer + 1, 1);
    END LOOP;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM cmdb.configuration_items WHERE lower(ident) = lower(candidate));
  END LOOP;
  RETURN candidate;
END;
$$;
--> statement-breakpoint

ALTER TABLE cmdb.configuration_items
  ADD COLUMN ident text,
  ADD COLUMN valid_from timestamp with time zone,
  ADD COLUMN valid_until timestamp with time zone,
  ADD COLUMN label text;
--> statement-breakpoint

-- One statement per CI, so each new ident sees the ones before it.
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT id FROM cmdb.configuration_items ORDER BY created_at, id LOOP
    UPDATE cmdb.configuration_items SET ident = cmdb.new_ci_ident() WHERE id = r.id;
  END LOOP;
END;
$$;
--> statement-breakpoint

UPDATE cmdb.configuration_items SET valid_from = created_at;
--> statement-breakpoint

ALTER TABLE cmdb.configuration_items
  ALTER COLUMN ident SET DEFAULT cmdb.new_ci_ident(),
  ALTER COLUMN ident SET NOT NULL,
  ALTER COLUMN valid_from SET DEFAULT now(),
  ALTER COLUMN valid_from SET NOT NULL,
  -- Generated idents match ^CI-[0-9A-Z]{8}$; an administrator may set any of these.
  ADD CONSTRAINT configuration_items_ident_format CHECK (ident ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'),
  ADD CONSTRAINT configuration_items_validity_order CHECK (valid_until IS NULL OR valid_until > valid_from);
--> statement-breakpoint
-- Unique regardless of case: "ci-7k3m9q2x" and "CI-7K3M9Q2X" are the same CI to a person.
CREATE UNIQUE INDEX configuration_items_ident_uq ON cmdb.configuration_items (lower(ident));
--> statement-breakpoint
CREATE INDEX configuration_items_validity_idx ON cmdb.configuration_items (valid_until, valid_from)
  WHERE deleted_at IS NULL;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Title attribute
-- ---------------------------------------------------------------------------
ALTER TABLE cmdb.ci_classes
  ADD COLUMN title_attribute_id uuid REFERENCES cmdb.ci_attribute_definitions (id) ON DELETE SET NULL;
--> statement-breakpoint
CREATE INDEX ci_classes_title_attribute_idx ON cmdb.ci_classes (title_attribute_id)
  WHERE title_attribute_id IS NOT NULL;
--> statement-breakpoint

-- Data types whose value reads as a name. The API checks the same list.
CREATE FUNCTION cmdb.title_data_type(p_data_type text) RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
  SELECT p_data_type IN ('text', 'enum', 'number', 'integer', 'date', 'datetime', 'ip', 'cidr');
$$;
--> statement-breakpoint

-- The title attribute must be a field of the class or one of its ancestors,
-- of a type that reads as a name. When a class moves to a parent that does not
-- provide its title attribute, the title is cleared (the API then picks the new
-- parent's and relabels the CIs).
CREATE FUNCTION cmdb.ci_classes_title_attribute() RETURNS trigger
LANGUAGE plpgsql SET search_path = cmdb, public AS $$
DECLARE
  def record;
BEGIN
  IF NEW.title_attribute_id IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT class_id, data_type INTO def FROM cmdb.ci_attribute_definitions WHERE id = NEW.title_attribute_id;
  -- The lineage as it will be: the row itself is not (or not yet so) in the table.
  IF NOT (def.class_id = NEW.id OR (NEW.parent_id IS NOT NULL AND cmdb.ci_class_is_a(NEW.parent_id, def.class_id))) THEN
    IF TG_OP = 'UPDATE' AND NEW.title_attribute_id IS NOT DISTINCT FROM OLD.title_attribute_id THEN
      NEW.title_attribute_id := NULL;
      RETURN NEW;
    END IF;
    RAISE EXCEPTION 'ci_classes: the title attribute must be defined on class % or one of its ancestors', NEW.key
      USING ERRCODE = 'check_violation', CONSTRAINT = 'ci_classes_title_attribute_in_lineage';
  END IF;
  IF NOT cmdb.title_data_type(def.data_type) THEN
    RAISE EXCEPTION 'ci_classes: a % attribute cannot be the title of class %', def.data_type, NEW.key
      USING ERRCODE = 'check_violation', CONSTRAINT = 'ci_classes_title_attribute_type';
  END IF;
  RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER ci_classes_title_attribute
  BEFORE INSERT OR UPDATE OF title_attribute_id, parent_id ON cmdb.ci_classes
  FOR EACH ROW EXECUTE FUNCTION cmdb.ci_classes_title_attribute();
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Fixed columns -> class attributes
-- ---------------------------------------------------------------------------

-- A lookup list for one of the old lookup tables, with the same ids. Returns
-- the list id (NULL when the table is empty).
CREATE FUNCTION cmdb.m0016_copy_lookup(p_table text, p_key text, p_name text) RETURNS uuid
LANGUAGE plpgsql SET search_path = cmdb, public AS $$
DECLARE
  list_key text := p_key;
  new_list uuid;
  n integer := 1;
  o record;
  value_key text;
  base text;
  k integer;
  i integer := 0;
  has_rows boolean;
BEGIN
  EXECUTE format('SELECT EXISTS (SELECT 1 FROM cmdb.%I)', p_table) INTO has_rows;
  IF NOT has_rows THEN
    RETURN NULL;
  END IF;
  WHILE EXISTS (SELECT 1 FROM cmdb.lookup_lists WHERE key = list_key) LOOP
    n := n + 1;
    list_key := p_key || '_' || n;
  END LOOP;
  INSERT INTO cmdb.lookup_lists (key, name, description)
  VALUES (list_key, p_name, format('Values of the former %s table (migration 0016)', p_table))
  RETURNING id INTO new_list;

  IF p_table = 'owners' THEN
    FOR o IN SELECT * FROM cmdb.owners ORDER BY lower(name) COLLATE "C", id LOOP
      base := btrim(lower(regexp_replace(o.name, '[^A-Za-z0-9]+', '_', 'g')), '_');
      IF base !~ '^[a-z]' THEN
        base := btrim('owner_' || base, '_');
      END IF;
      base := rtrim(left(base, 56), '_');
      value_key := base;
      k := 1;
      WHILE EXISTS (SELECT 1 FROM cmdb.lookup_list_values WHERE list_id = new_list AND key = value_key) LOOP
        k := k + 1;
        value_key := base || '_' || k;
      END LOOP;
      i := i + 1;
      INSERT INTO cmdb.lookup_list_values (id, list_id, key, name, description, sort_order, is_active)
      VALUES (o.id, new_list, value_key, coalesce(nullif(btrim(o.name), ''), 'Owner ' || i),
              nullif(concat_ws(', ', CASE o.kind WHEN 'team' THEN 'Team' ELSE 'Person' END, o.email), ''),
              i * 10, o.is_active);
    END LOOP;
  ELSE
    EXECUTE format(
      'INSERT INTO cmdb.lookup_list_values (id, list_id, key, name, description, sort_order, is_active)
       SELECT id, $1, key, name, %s, sort_order, is_active FROM cmdb.%I',
      CASE p_table WHEN 'locations' THEN 'coalesce(description, address)' ELSE 'description' END, p_table)
    USING new_list;
  END IF;
  RETURN new_list;
END;
$$;
--> statement-breakpoint

DO $$
DECLARE
  -- key, label, old column, data type, lookup table, validation, required, sort order
  spec constant jsonb := '[
    {"key": "name", "label": "Name", "col": "name", "type": "text", "validation": {"maxLength": 200, "pattern": "\\S"}, "required": true, "sort": -100},
    {"key": "status", "label": "Status", "col": "status_id", "type": "lookup", "table": "statuses", "required": true, "sort": -90},
    {"key": "environment", "label": "Environment", "col": "environment_id", "type": "lookup", "table": "environments", "sort": -80},
    {"key": "owner", "label": "Owner", "col": "owner_id", "type": "lookup", "table": "owners", "sort": -70},
    {"key": "location", "label": "Location", "col": "location_id", "type": "lookup", "table": "locations", "sort": -60},
    {"key": "hostname", "label": "Hostname", "col": "hostname", "type": "text", "validation": {"maxLength": 253, "pattern": "^[A-Za-z0-9]([A-Za-z0-9._-]{0,252})$"}, "sort": -50},
    {"key": "ip_address", "label": "IP address", "col": "ip_address", "type": "ip", "sort": -40},
    {"key": "serial_number", "label": "Serial number", "col": "serial_number", "type": "text", "validation": {"maxLength": 200}, "sort": -30},
    {"key": "notes", "label": "Notes", "col": "notes", "type": "text", "validation": {"maxLength": 4000}, "sort": 10000}
  ]';
  lists constant jsonb := '{"statuses": ["status", "Status"], "environments": ["environment", "Environment"],
                            "owners": ["owner", "Owner"], "locations": ["location", "Location"]}';
  f jsonb;
  list_ids jsonb := '{}';
  field_list uuid;
  target record;
  field_key text;
  n integer;
  def_id uuid;
  hex text;
  pg_type text;
  stmt text;
  stmts text[] := ARRAY[]::text[];
  notes jsonb := '[]'::jsonb;
  moved bigint;
  field_moved bigint;
  expected bigint;
  total_moved bigint := 0;
  nulls bigint;
  v record;
BEGIN
  -- Engine views read the columns that are about to go; `shadoucmdb migrate` rebuilds them.
  FOR v IN
    SELECT format('%I.%I', ns.nspname, c.relname) AS name
    FROM pg_class c JOIN pg_namespace ns ON ns.oid = c.relnamespace
    WHERE c.relkind = 'v' AND obj_description(c.oid, 'pg_class') LIKE 'shadoucmdb:%'
  LOOP
    stmt := format('DROP VIEW %s', v.name);
    EXECUTE stmt;
    stmts := stmts || stmt;
  END LOOP;

  FOR f IN SELECT * FROM jsonb_array_elements(spec) LOOP
    field_list := NULL;
    IF f ? 'table' THEN
      field_list := cmdb.m0016_copy_lookup(f->>'table', lists->(f->>'table')->>0, lists->(f->>'table')->>1);
      IF field_list IS NOT NULL THEN
        list_ids := list_ids || jsonb_build_object(f->>'key', field_list);
      END IF;
    END IF;
    pg_type := CASE f->>'type' WHEN 'text' THEN 'text' WHEN 'ip' THEN 'inet' ELSE 'uuid' END;
    field_moved := 0;

    -- name: every root class. Others: the topmost classes whose CIs (deleted
    -- ones included) hold a value; a CI's lineage contains exactly one of them.
    FOR target IN EXECUTE format(
      $q$
      WITH holding AS (
        SELECT DISTINCT class_id FROM cmdb.configuration_items WHERE %1$I IS NOT NULL
      )
      SELECT c.id, c.key, a.key AS area
      FROM cmdb.ci_classes c JOIN cmdb.areas a ON a.id = c.area_id
      WHERE CASE WHEN %2$L = 'name' THEN c.parent_id IS NULL
                 ELSE c.id IN (SELECT class_id FROM holding)
                      AND NOT EXISTS (SELECT 1 FROM holding h, cmdb.ci_class_lineage(c.id) l
                                      WHERE l.class_id = h.class_id AND l.depth > 0) END
      ORDER BY a.key, c.key
      $q$, f->>'col', f->>'key')
    LOOP
      -- A key already used in the lineage (above or below) gets a suffix.
      field_key := f->>'key';
      n := 1;
      WHILE EXISTS (
        SELECT 1 FROM cmdb.ci_attribute_definitions d
        WHERE d.key = field_key AND (cmdb.ci_class_is_a(target.id, d.class_id) OR cmdb.ci_class_is_a(d.class_id, target.id))
      ) LOOP
        n := n + 1;
        field_key := (f->>'key') || '_' || n;
      END LOOP;
      IF n > 1 THEN
        notes := notes || jsonb_build_object('kind', 'warning', 'message',
          format('%s.%s: the key "%s" is already used in this lineage; the field is "%s"',
                 target.area, target.key, f->>'key', field_key));
      END IF;

      INSERT INTO cmdb.ci_attribute_definitions
        (class_id, key, label, data_type, is_required, lookup_list_id, validation, sort_order)
      VALUES (target.id, field_key, f->>'label', f->>'type', coalesce((f->>'required')::boolean, false),
              CASE WHEN f->>'type' = 'lookup' THEN field_list END, f->'validation', (f->>'sort')::integer)
      RETURNING id INTO def_id;
      hex := replace(def_id::text, '-', '');

      stmt := format('ALTER TABLE %I.%I ADD COLUMN %I %s', target.area, target.key, field_key, pg_type);
      EXECUTE stmt;
      stmts := stmts || stmt;
      EXECUTE format('UPDATE %I.%I t SET %I = ci.%I FROM cmdb.configuration_items ci
                      WHERE ci.id = t.id AND ci.%I IS NOT NULL',
                     target.area, target.key, field_key, f->>'col', f->>'col');
      GET DIAGNOSTICS moved = ROW_COUNT;
      EXECUTE format('SELECT count(*) FROM cmdb.configuration_items WHERE %I IS NOT NULL AND cmdb.ci_class_is_a(class_id, $1)',
                     f->>'col') INTO expected USING target.id;
      IF moved <> expected THEN
        RAISE EXCEPTION 'moving %.% failed: % CIs hold a value, % written to %.%',
          target.key, f->>'col', expected, moved, target.area, target.key;
      END IF;
      field_moved := field_moved + moved;

      IF f->>'type' = 'lookup' THEN
        stmt := format('ALTER TABLE %I.%I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES cmdb.lookup_list_values (id) ON DELETE RESTRICT',
                       target.area, target.key, 'fk_' || hex, field_key);
        EXECUTE stmt;
        stmts := stmts || stmt;
        stmt := format('CREATE INDEX %I ON %I.%I (%I)', 'ix_' || hex, target.area, target.key, field_key);
        EXECUTE stmt;
        stmts := stmts || stmt;
      END IF;

      IF coalesce((f->>'required')::boolean, false) THEN
        EXECUTE format('SELECT count(*) FROM %I.%I WHERE %I IS NULL', target.area, target.key, field_key) INTO nulls;
        IF nulls = 0 THEN
          stmt := format('ALTER TABLE %I.%I ALTER COLUMN %I SET NOT NULL', target.area, target.key, field_key);
          EXECUTE stmt;
          stmts := stmts || stmt;
        ELSE
          -- Only possible for a root class without CIs of its own sharing a table
          -- with inconsistent rows; kept nullable rather than failing the upgrade.
          notes := notes || jsonb_build_object('kind', 'not_null_skipped', 'rows', nulls, 'message',
            format('%s.%s stays nullable: %s CIs have no value', target.key, field_key, nulls));
        END IF;
      END IF;

      IF f->>'key' = 'name' THEN
        -- The title of this root class and of every class below it.
        UPDATE cmdb.ci_classes c SET title_attribute_id = def_id WHERE cmdb.ci_class_is_a(c.id, target.id);
      END IF;
    END LOOP;

    EXECUTE format('SELECT count(*) FROM cmdb.configuration_items WHERE %I IS NOT NULL', f->>'col') INTO expected;
    IF field_moved <> expected THEN
      RAISE EXCEPTION 'moving % failed: % CIs hold a value, % were copied', f->>'col', expected, field_moved;
    END IF;
    IF expected > 0 THEN
      notes := notes || jsonb_build_object('kind', 'data_moved', 'rows', expected, 'message',
        format('%s values of configuration_items.%s copied into field "%s" and verified', expected, f->>'col', f->>'key'));
    END IF;
    total_moved := total_moved + field_moved;
  END LOOP;

  UPDATE cmdb.configuration_items SET label = name;

  -- The lists' keys, for rewriting the stored UI settings below (same transaction).
  DROP TABLE IF EXISTS pg_temp.m0016_lists;
  CREATE TEMPORARY TABLE m0016_lists ON COMMIT DROP AS
  SELECT e.key AS field, l.key AS list_key
  FROM jsonb_each_text(list_ids) e JOIN cmdb.lookup_lists l ON l.id = e.value::uuid;

  -- Recorded when it changed a table (a fresh install has none).
  IF cardinality(stmts) > 0 THEN
    INSERT INTO cmdb.schema_changes (actor_type, actor_name, summary, statements, impact)
    VALUES ('system', 'migration 0016',
            format('Migration 0016: fixed CI columns moved into class fields (%s values)', total_moved),
            stmts, notes);
  END IF;
END;
$$;
--> statement-breakpoint

DROP FUNCTION cmdb.m0016_copy_lookup(text, text, text);
--> statement-breakpoint

ALTER TABLE cmdb.configuration_items
  DROP COLUMN search_vector,
  DROP COLUMN name,
  DROP COLUMN status_id,
  DROP COLUMN environment_id,
  DROP COLUMN owner_id,
  DROP COLUMN location_id,
  DROP COLUMN hostname,
  DROP COLUMN ip_address,
  DROP COLUMN serial_number,
  DROP COLUMN notes;
--> statement-breakpoint

UPDATE cmdb.configuration_items SET label = ident WHERE label IS NULL OR btrim(label) = '';
--> statement-breakpoint
ALTER TABLE cmdb.configuration_items
  ALTER COLUMN label SET NOT NULL,
  ADD CONSTRAINT configuration_items_label_not_blank CHECK (length(btrim(label)) > 0),
  ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', label || ' ' || ident)) STORED;
--> statement-breakpoint
CREATE INDEX configuration_items_live_label_idx ON cmdb.configuration_items (lower(label), id) WHERE deleted_at IS NULL;
--> statement-breakpoint
CREATE INDEX configuration_items_class_label_idx ON cmdb.configuration_items (class_id, lower(label)) WHERE deleted_at IS NULL;
--> statement-breakpoint
CREATE INDEX configuration_items_search_idx ON cmdb.configuration_items USING gin (search_vector);
--> statement-breakpoint
CREATE INDEX configuration_items_label_trgm_idx ON cmdb.configuration_items USING gin (label gin_trgm_ops);
--> statement-breakpoint
CREATE INDEX configuration_items_ident_trgm_idx ON cmdb.configuration_items USING gin (ident gin_trgm_ops);
--> statement-breakpoint

ALTER TABLE cmdb.configuration_items ENABLE TRIGGER configuration_items_set_updated_at;
--> statement-breakpoint
ALTER TABLE cmdb.ci_classes ENABLE TRIGGER ci_classes_set_updated_at;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Stored UI settings: the new field names
-- ---------------------------------------------------------------------------
-- Built-in fields that became attributes are "attributes.<key>"; list columns
-- and sorts on the name use the label. Status, environment and location
-- filters become lookup filters; count_by_status / count_by_environment
-- widgets become count_by_lookup widgets on the migrated lists.
CREATE OR REPLACE FUNCTION pg_temp.m0016_field(p text) RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE p
    WHEN 'name' THEN 'attributes.name' WHEN 'status' THEN 'attributes.status'
    WHEN 'environment' THEN 'attributes.environment' WHEN 'owner' THEN 'attributes.owner'
    WHEN 'location' THEN 'attributes.location' WHEN 'hostname' THEN 'attributes.hostname'
    WHEN 'ipAddress' THEN 'attributes.ip_address' WHEN 'serialNumber' THEN 'attributes.serial_number'
    WHEN 'notes' THEN 'attributes.notes' ELSE p END;
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION pg_temp.m0016_fields(p jsonb, columns boolean) RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$
  -- Mapped, first occurrence kept ("name" and "attributes.name" become one entry).
  SELECT coalesce(jsonb_agg(d.f ORDER BY d.n), '[]'::jsonb)
  FROM (
    SELECT DISTINCT ON (x.f) x.f, x.n FROM (
      SELECT CASE WHEN columns AND e.v = 'name' THEN 'label' ELSE pg_temp.m0016_field(e.v) END AS f, e.n
      FROM jsonb_array_elements_text(CASE WHEN jsonb_typeof(p) = 'array' THEN p ELSE '[]' END) WITH ORDINALITY AS e(v, n)
    ) x ORDER BY x.f, x.n
  ) d;
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION pg_temp.m0016_sort(p jsonb) RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE WHEN jsonb_typeof(p) = 'object' AND p->>'field' IN ('name', 'hostname', 'ipAddress', 'serialNumber', 'statusName')
              THEN jsonb_set(p, '{field}', '"label"') ELSE p END;
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION pg_temp.m0016_filters(p jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$
  SELECT CASE WHEN jsonb_typeof(p) <> 'object' THEN p ELSE
    (p - 'statusKeys' - 'environmentKeys' - 'locationKeys') || CASE WHEN lk = '{}'::jsonb THEN '{}'::jsonb
                                                                 ELSE jsonb_build_object('lookups', lk) END
  END
  FROM (
    SELECT coalesce(jsonb_object_agg(coalesce(l.list_key, m.field), p->m.prop), '{}'::jsonb) AS lk
    FROM (VALUES ('statusKeys', 'status'), ('environmentKeys', 'environment'), ('locationKeys', 'location')) AS m(prop, field)
    LEFT JOIN m0016_lists l ON l.field = m.field
    WHERE jsonb_typeof(p->m.prop) = 'array' AND jsonb_array_length(p->m.prop) > 0
  ) x;
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION pg_temp.m0016_search(p jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$
  SELECT CASE WHEN jsonb_typeof(p) <> 'object' THEN p ELSE
    p || jsonb_strip_nulls(jsonb_build_object(
      'filters', CASE WHEN p ? 'filters' THEN pg_temp.m0016_filters(p->'filters') END,
      'sort', CASE WHEN p ? 'sort' THEN pg_temp.m0016_sort(p->'sort') END))
  END;
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION pg_temp.m0016_widget(w jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$
  SELECT CASE
    WHEN w->>'type' IN ('count_by_status', 'count_by_environment') THEN
      w || jsonb_build_object('type', 'count_by_lookup', 'lookupListKey',
        coalesce((SELECT l.list_key FROM m0016_lists l
                  WHERE l.field = CASE w->>'type' WHEN 'count_by_status' THEN 'status' ELSE 'environment' END),
                 CASE w->>'type' WHEN 'count_by_status' THEN 'status' ELSE 'environment' END))
    WHEN w ? 'search' THEN w || jsonb_build_object('search', pg_temp.m0016_search(w->'search'))
    ELSE w
  END;
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION pg_temp.m0016_settings(s jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$
  SELECT s
    || CASE WHEN jsonb_typeof(s->'dashboard'->'widgets') = 'array' THEN jsonb_build_object('dashboard',
         (s->'dashboard') || jsonb_build_object('widgets',
           (SELECT coalesce(jsonb_agg(pg_temp.m0016_widget(w) ORDER BY n), '[]') FROM jsonb_array_elements(s->'dashboard'->'widgets') WITH ORDINALITY AS e(w, n))))
       ELSE '{}' END
    || CASE WHEN jsonb_typeof(s->'listViews') = 'array' THEN jsonb_build_object('listViews',
         (SELECT coalesce(jsonb_agg(
            v || jsonb_strip_nulls(jsonb_build_object(
              'columns', CASE WHEN v ? 'columns' THEN pg_temp.m0016_fields(v->'columns', true) END,
              'defaultSort', CASE WHEN jsonb_typeof(v->'defaultSort') = 'object' THEN pg_temp.m0016_sort(v->'defaultSort') END,
              'defaultFilters', CASE WHEN v ? 'defaultFilters' THEN pg_temp.m0016_filters(v->'defaultFilters') END))
            ORDER BY n), '[]')
          FROM jsonb_array_elements(s->'listViews') WITH ORDINALITY AS e(v, n)))
       ELSE '{}' END
    || CASE WHEN jsonb_typeof(s->'layouts') = 'array' THEN jsonb_build_object('layouts',
         (SELECT coalesce(jsonb_agg(
            l || jsonb_strip_nulls(jsonb_build_object(
              'panels', CASE WHEN jsonb_typeof(l->'panels') = 'array' THEN
                (SELECT coalesce(jsonb_agg(p || jsonb_build_object('fields', pg_temp.m0016_fields(p->'fields', false)) ORDER BY pn), '[]')
                 FROM jsonb_array_elements(l->'panels') WITH ORDINALITY AS q(p, pn)) END,
              'hiddenFields', CASE WHEN l ? 'hiddenFields' THEN pg_temp.m0016_fields(l->'hiddenFields', false) END,
              'readOnlyFields', CASE WHEN l ? 'readOnlyFields' THEN pg_temp.m0016_fields(l->'readOnlyFields', false) END))
            ORDER BY n), '[]')
          FROM jsonb_array_elements(s->'layouts') WITH ORDINALITY AS e(l, n)))
       ELSE '{}' END;
$$;
--> statement-breakpoint
DO $$
DECLARE
  current record;
  updated jsonb;
BEGIN
  SELECT version, settings INTO current FROM cmdb.ui_settings FOR UPDATE;
  IF NOT FOUND THEN
    RETURN;
  END IF;
  updated := pg_temp.m0016_settings(current.settings);
  IF updated IS DISTINCT FROM current.settings THEN
    INSERT INTO cmdb.ui_settings_versions (version, settings, actor_type, actor_name, comment)
    SELECT max(version) + 1, updated, 'system', 'migration 0016',
           'Field names of the barebone CI core (name, status, hostname ... are class fields now)'
    FROM cmdb.ui_settings_versions;
    UPDATE cmdb.ui_settings
    SET settings = updated, version = (SELECT max(version) FROM cmdb.ui_settings_versions),
        updated_at = now(), updated_by_id = NULL, updated_by_name = 'migration 0016';
  END IF;
END;
$$;
--> statement-breakpoint

-- The helpers live in this session's temporary schema; the connection may run more migrations.
DROP FUNCTION pg_temp.m0016_settings(jsonb);
DROP FUNCTION pg_temp.m0016_widget(jsonb);
DROP FUNCTION pg_temp.m0016_search(jsonb);
DROP FUNCTION pg_temp.m0016_filters(jsonb);
DROP FUNCTION pg_temp.m0016_sort(jsonb);
DROP FUNCTION pg_temp.m0016_fields(jsonb, boolean);
DROP FUNCTION pg_temp.m0016_field(text);
DROP TABLE pg_temp.m0016_lists;
