// Regenerates the vendored Lucide icon subset (src/icons/lucide.ts, src/icons/lucide-css.css and
// src/icons/LICENSE.txt) from an unpacked lucide-static release. Nothing here runs at build time:
// the generated files are committed, so builds stay offline and air-gapped installs need nothing.
//
//   curl -sLO https://registry.npmjs.org/lucide-static/-/lucide-static-1.51.0.tgz
//   tar xzf lucide-static-1.51.0.tgz
//   node scripts/vendor-lucide.mjs ./package
//
// To add an icon, add its Lucide name to ICONS (or CSS_ICONS when a stylesheet needs it) and re-run.
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/** Icons the <Icon> component can draw. Keep sorted. */
const ICONS = [
  "app-window",
  "arrow-down",
  "arrow-down-to-line",
  "arrow-left",
  "arrow-left-right",
  "arrow-right",
  "arrow-up",
  "arrow-up-to-line",
  "box",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "circle",
  "circle-alert",
  "circle-check",
  "circle-x",
  "cloud",
  "container",
  "database",
  "ellipsis",
  "equal",
  "file-text",
  "grip-horizontal",
  "grip-vertical",
  "hard-drive",
  "inbox",
  "info",
  "lock",
  "map-pin",
  "menu",
  "minus",
  "monitor",
  "network",
  "pencil",
  "plus",
  "search",
  "server",
  "smartphone",
  "square",
  "triangle-alert",
  "upload",
  "user",
  "x",
];

/** Icons a stylesheet draws as a CSS mask (pseudo-elements that cannot hold an <svg>). */
const CSS_ICONS = ["chevron-down", "chevron-right", "circle-alert", "circle-check", "info", "triangle-alert"];

const src = process.argv[2];
if (!src) {
  console.error("usage: node scripts/vendor-lucide.mjs <unpacked lucide-static package dir>");
  process.exit(1);
}
const pkg = JSON.parse(readFileSync(join(src, "package.json"), "utf8"));
if (pkg.name !== "lucide-static") throw new Error(`${src} is ${pkg.name}, not lucide-static`);
const nodes = JSON.parse(readFileSync(join(src, "icon-nodes.json"), "utf8"));

const missing = [...ICONS, ...CSS_ICONS].filter((n) => !nodes[n]);
if (missing.length) throw new Error(`not in lucide-static ${pkg.version}: ${missing.join(", ")}`);

const out = new URL("../src/icons/", import.meta.url);
const header = (comment) =>
  `${comment} Generated by scripts/vendor-lucide.mjs from lucide-static ${pkg.version} (ISC, see LICENSE.txt). Do not edit.\n`;

const ts =
  header("//") +
  "// Each icon is Lucide's own element list on its 24×24 grid, unmodified.\n\n" +
  "export type IconNode = [tag: \"path\" | \"circle\" | \"rect\" | \"line\" | \"polyline\" | \"polygon\" | \"ellipse\", attrs: Record<string, string>][];\n\n" +
  "export const ICONS = {\n" +
  ICONS.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(nodes[n])},`).join("\n") +
  "\n} satisfies Record<string, IconNode>;\n\n" +
  "export type IconName = keyof typeof ICONS;\n";
writeFileSync(new URL("lucide.ts", out), ts);

const svg = (n) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">` +
  nodes[n].map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(" ")}/>`).join("") +
  "</svg>";
const css =
  header("/*").replace(/\n$/, " */\n") +
  "/* Use as `mask: var(--icon-…) center / contain no-repeat; background: currentColor`. */\n" +
  ":root {\n" +
  CSS_ICONS.map((n) => `  --icon-${n}: url("data:image/svg+xml,${encodeURIComponent(svg(n)).replace(/'/g, "%27")}");`).join("\n") +
  "\n}\n";
writeFileSync(new URL("lucide-css.css", out), css);

copyFileSync(join(src, "LICENSE"), new URL("LICENSE.txt", out));
console.log(`lucide-static ${pkg.version}: ${ICONS.length} icons, ${CSS_ICONS.length} CSS icons`);
