// Regenerates the vendored Lucide icon subset (src/icons/lucide.ts, src/icons/lucide-css.css and
// src/icons/LICENSE.txt) from the lucide-static release archive. Nothing here runs at build time:
// the generated files are committed, so builds stay offline and air-gapped installs need nothing.
//
//   curl -sLO https://registry.npmjs.org/lucide-static/-/lucide-static-1.51.0.tgz
//   node scripts/vendor-lucide.mjs lucide-static-1.51.0.tgz
//
// The archive must match ARCHIVE_SHA256 (the hash recorded in THIRD_PARTY_NOTICES) before anything
// is unpacked or generated. Moving to another Lucide release means updating the version and hash
// here and in THIRD_PARTY_NOTICES in the same change.
//
// To add an icon, add its Lucide name to ICONS (or CSS_ICONS when a stylesheet needs it) and re-run.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** The pinned release: lucide-static-<VERSION>.tgz from registry.npmjs.org. */
const VERSION = "1.51.0";
const ARCHIVE_SHA256 = "6936026d1512256483161ae999982e3be3d5d74226996c4ec7447e901726a2d8";

/** Icons the <Icon> component can draw. Keep sorted. */
const ICONS = [
  "app-window",
  "arrow-down",
  "arrow-down-to-line",
  "arrow-left",
  "arrow-left-right",
  "arrow-right",
  "arrow-up",
  "arrow-up-down",
  "arrow-up-to-line",
  "box",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "circle",
  "circle-alert",
  "circle-check",
  "circle-x",
  "cloud",
  "columns-3",
  "container",
  "database",
  "ellipsis",
  "equal",
  "file-text",
  "grip-horizontal",
  "grip-vertical",
  "hard-drive",
  "inbox",
  "info",
  "layers",
  "layout-dashboard",
  "list",
  "lock",
  "log-out",
  "map-pin",
  "menu",
  "minus",
  "monitor",
  "network",
  "panel-left-close",
  "panel-left-open",
  "pencil",
  "plus",
  "scroll-text",
  "search",
  "server",
  "settings",
  "smartphone",
  "square",
  "triangle-alert",
  "upload",
  "user",
  "x",
];

/** Icons a stylesheet draws as a CSS mask (pseudo-elements that cannot hold an <svg>). */
const CSS_ICONS = ["chevron-down", "chevron-right", "circle-alert", "circle-check", "info", "triangle-alert"];

const archive = process.argv[2];
if (!archive) {
  console.error(`usage: node scripts/vendor-lucide.mjs <lucide-static-${VERSION}.tgz>`);
  process.exit(1);
}
const digest = createHash("sha256").update(readFileSync(archive)).digest("hex");
if (digest !== ARCHIVE_SHA256) {
  console.error(`${archive}: SHA-256 ${digest} does not match the pinned lucide-static ${VERSION} (${ARCHIVE_SHA256}). Nothing was generated.`);
  process.exit(1);
}
const work = mkdtempSync(join(tmpdir(), "vendor-lucide-"));
process.on("exit", () => rmSync(work, { recursive: true, force: true }));
execFileSync("tar", ["-xzf", archive, "-C", work, "package/package.json", "package/icon-nodes.json", "package/LICENSE"]);
const src = join(work, "package");
const pkg = JSON.parse(readFileSync(join(src, "package.json"), "utf8"));
if (pkg.name !== "lucide-static" || pkg.version !== VERSION) throw new Error(`${archive} holds ${pkg.name} ${pkg.version}, not lucide-static ${VERSION}`);
const nodes = JSON.parse(readFileSync(join(src, "icon-nodes.json"), "utf8"));

const missing = [...ICONS, ...CSS_ICONS].filter((n) => !nodes[n]);
if (missing.length) throw new Error(`not in lucide-static ${pkg.version}: ${missing.join(", ")}`);

const out = new URL("../src/icons/", import.meta.url);
const header = (comment) =>
  `${comment} Generated by scripts/vendor-lucide.mjs from lucide-static ${pkg.version} (ISC, see LICENSE.txt). Do not edit.\n`;

const ts =
  header("//") +
  "// Each icon is Lucide's own element list on its 24×24 grid, unmodified.\n\n" +
  "export type IconNode = [tag: \"path\" | \"circle\" | \"rect\" | \"line\" | \"polyline\" | \"polygon\" | \"ellipse\", attrs: Record<string, string>][];\n\n" +
  "export const ICONS = {\n" +
  ICONS.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(nodes[n])},`).join("\n") +
  "\n} satisfies Record<string, IconNode>;\n\n" +
  "export type IconName = keyof typeof ICONS;\n";
writeFileSync(new URL("lucide.ts", out), ts);

const svg = (n) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">` +
  nodes[n].map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(" ")}/>`).join("") +
  "</svg>";
const css =
  header("/*").replace(/\n$/, " */\n") +
  "/* Use as `mask: var(--icon-…) center / contain no-repeat; background: currentColor`. */\n" +
  ":root {\n" +
  CSS_ICONS.map((n) => `  --icon-${n}: url("data:image/svg+xml,${encodeURIComponent(svg(n)).replace(/'/g, "%27")}");`).join("\n") +
  "\n}\n";
writeFileSync(new URL("lucide-css.css", out), css);

copyFileSync(join(src, "LICENSE"), new URL("LICENSE.txt", out));
console.log(`lucide-static ${pkg.version}: ${ICONS.length} icons, ${CSS_ICONS.length} CSS icons`);
